source "https://rubygems.org"

# Specify your gem's dependencies in palapala_pdf.gemspec.
gemspec path: "../.."

gem "puma"
gem "propshaft"
gem "sqlite3", "~> 2.1"

# Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
gem "rubocop-rails-omakase", require: false

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"
